### PR TITLE
Release of monet flash

### PR DESCRIPTION
**Pull request by larrytech7**
Preparing the release of a possible version 0.5 of the monetflash app. This is actually the first stable version of the app.

### CODE REVIEW

**Comment by larrytech7** [comment]
man merge this thing

**Comment by lewisitor** [comment]
just cloned the repo on my Android Studio, but i get errors like "cannot
find R " , the R resource used by Ids and other stuffs

**Comment by larrytech7** [comment]
You need to upgrade your version of gradle and sync project. Also check your compile and build SDK versions for what i use.

**Comment by lewisitor** [comment]
Ok, just refreshed everything, it's ok now

**Comment by larrytech7** [comment]
have you built the app yet? are you making tests?

**Comment by larrytech7** [comment]
why is this pull request still open? ~You haven't merged with yours why?

**Pull request merged**
